// define application array
const apps = [{
  name: 'ESB',
  fullName: '企业服务总线',
  category: 'IT中台',
  url: 'http://tech.envision-aesc.cn/esb-web',
  intro: '企业服务总线，系统间接口和服务集成，提供同步和异步服务调用，支持HTTP/Web Service/MQ等集成方式',
},
{
  name: 'DDS',
  fullName: '数据决策系统',
  category: 'IT中台',
  url: 'http://bi.envision-aesc.cn/',
  intro: '数据决策系统、报表',
},
{
  name: '屏幕管理系统',
  fullName: '屏幕管理系统',
  category: 'IT中台',
  url: '',
  intro: '屏幕、大屏管理',
},
{
  name: '中台',
  fullName: 'modelSystem',
  category: 'IT中台',
  url: 'http://tech.envision-aesc.cn/modelSystem/felix',
  intro: '模型中台',
},
{
  name: 'IOC',
  fullName: '消息中心',
  category: 'IT中台',
  url: 'http://10.201.129.14/message',
  intro: '提供消息服务',
},
{
  name: 'IOC',
  fullName: '告警中心',
  category: 'IT中台',
  url: 'http://10.201.129.14/alarm',
  intro: '提供告警服务，支持邮件、企微、短信',
},
{
  name: 'IOC',
  fullName: 'Base项目',
  category: 'IT中台',
  url: 'http://10.201.129.14/aesc',
  intro: '中台基础模块',
},
{
  name: 'IOC',
  fullName: '工单系统',
  category: 'IT中台',
  url: 'http://10.201.129.14/work-order',
  intro: '工作流处理',
},
{
  name: 'IOC',
  fullName: '积分系统',
  category: 'IT中台',
  url: 'http://10.201.129.14/integral',
  intro: '包括积分规则管理 积分商城',
},
{
  name: 'IOC',
  fullName: '全球培训生',
  category: 'IT中台',
  url: 'http://10.201.129.14/work-order',
  intro: '培训生周报、月报管理',
},
{
  name: 'EHS',
  fullName: '安心睡系统',
  category: 'IT中台',
  url: 'https://app-portal-cn5.envisioniot.com/',
  intro: '告警管理，先兆提报，巡检管理，风险数据查询，设备管理',
},
{
  name: 'EHS',
  fullName: '隐患提报系统',
  category: 'IT中台',
  url: 'https://tp.envision-aesc.cn:3443/work-order-h5/ehs/?code=ZfI6w2G5eQQhu30vo6rp-NDhugda72wv2Qq47iKqRSo&state=1000012',
  intro: '隐患提报，隐患整改，流程跟踪',
},
{
  name: '2PP',
  fullName: '远景动力知识平台',
  category: 'PMO',
  url: 'http://tech.envision-aesc.cn/tpp/index',
  intro: '知识管理平台 ：经验教训结构化、驱动标准文件更新、工厂标准化；文控管理平台：体系文件、技术文件全生命周期管理',
},
{
  name: 'KTM    ',
  fullName: '关键任务管理系统',
  category: 'PMO',
  url: 'http://tech.envision-aesc.cn/ktm/index',
  intro: '关键任务、事项跟踪，会议纪要管理',
},
{
  name: 'Quotation',
  fullName: '报价系统',
  category: '财务',
  url: 'http://apaas.envision-aesc.cn/account/signin?returnurl=%2f',
  intro: '公司产品报价系统',
},
{
  name: '报销系统',
  fullName: '汇联易报销系统',
  category: '财务',
  url: 'https://console-a2.huilianyi.com/main/dashboard',
  intro: '费用报销',
},
{
  name: 'PMS',
  fullName: '客户项目管理系统',
  category: '大研发',
  url: 'http://g-pms.envision-aesc.cn:1080/login',
  intro: '管理客户项目',
},
{
  name: 'PLM',
  fullName: '产品生命周期管理',
  category: '大研发',
  url: 'http://awc.envision-aesc.cn:3000/',
  intro: '物料管理、BOM管理、BOP管理、BOE管理、研发项目管理',
},
{
  name: 'ECM',
  fullName: 'Enterprise Change Management',
  category: '大研发',
  url: 'https://ecm.envision-aesc.cn/3dpassport/login',
  intro: '企业变更管理系统，管理C样以后所有变更',
},
{
  name: 'COA',
  fullName: '研发物料管理系统',
  category: '大研发',
  url: 'http://coa.envision-aesc.cn:8085/login',
  intro: '供应商管理，物料管理，供应商物料查询、COA管控、电子签章',
},
{
  name: 'e-package',
  fullName: '样品电芯PACKAGE设计管理系统',
  category: '大研发',
  url: 'http://epk.envision-aesc.cn/login?redirect=%2Findex',
  intro: 'C样之前样品电芯PACKAGE设计管理系统',
},
{
  name: 'LIMS',
  fullName: '实验室信息管理系统',
  category: '大研发',
  url: 'http://10.201.1.23:9992/#/login',
  intro: '样品测试全流程管控系统',
},
{
  name: '摩卡校招',
  fullName: '校园招聘',
  category: '大运营',
  url: 'https://app.mokahr.com/login?redirectUrl=%2F',
  intro: 'SaaS智能化校园招聘管理系统（MOKA）',
},
{
  name: '数字学院',
  fullName: '规则考试、培训、学习平台',
  category: '大运营',
  url: 'https://aesc.yunxuetang.cn/login.html',
  intro: 'SaaS数字化企业学习培训考试管理（云学堂）',
},
{
  name: '绩效系统',
  fullName: '绩效',
  category: '大运营',
  url: 'http://kpi.envision-aesc.cn:9006/',
  intro: '绩效目标设定、纵向考核评估',
},
{
  name: '远景精神',
  fullName: '远景精神',
  category: '大运营',
  url: 'https://spirit.envision-aesc.cn/#/',
  intro: '360°评价反馈管理',
},
{
  name: '社招系统',
  fullName: '社招网站系统',
  category: '大运营',
  url: 'https://talentplatform.envision-aesc.cn/#/',
  intro: '社会招聘管理系统',
},
{
  name: 'TMS',
  fullName: '运输管理系统',
  category: '大运营',
  url: 'https://tms.envision-aesc.cn:8118/scm.cloud.web',
  intro: '国内成品物料运输管理',
},
{
  name: 'SRM',
  fullName: '供应商管理系统',
  category: '大运营',
  url: 'https://srm.envision-aesc.cn:9543',
  intro: '供应商管理、采购业务协同、质量业务协同、供应链业务协同',
},
{
  name: 'SAP',
  fullName: 'ERP企业资源计划管理系统',
  category: '大运营',
  url: '客户端登录',
  intro: '主要包含几大模块功能:\n1. 财务管理模块，主要包含应收、应付、总账管理、利润成本分析、产品成本、获利分析等功能。\n2. 物料管理模块，主要有采购、库房与库存管理、供应商评价等管理功能。\n3. 销售与分销模块，包括销售计划、询价报价、订单管理、运输发货、发票等的管理。\n4. 生产计划模块，可实现对工厂数据、生产计划、能力计划、成本核算等的管理。\n5. 质量管理模块，可提供质量计划、质量检测、质量控制、质量文档等功能。\n6. EWM仓库管理模块，高效管理仓库中的库存并支持货物移动处理。',
},
{
  name: 'OA',
  fullName: 'OA',
  category: '大运营',
  url: 'https://doa.envision-aesc.cn/',
  intro: '统一办公门户，电子流程',
},
{
  name: 'EDA-江阴',
  fullName: '工程数据分析系统',
  category: '大制造',
  url: 'http://eda-jy.envision-aesc.cn/#/login',
  intro: '为工艺、研发、质量等团队提供数据分析的系统',
},
{
  name: 'EDA-Ordos',
  fullName: '工程数据分析系统',
  category: '大制造',
  url: 'http://eda-ordos.envision-aesc.cn/#/login',
  intro: '为工艺、研发、质量等团队提供数据分析的系统',
},
{
  name: 'EDA-十堰',
  fullName: '工程数据分析系统',
  category: '大制造',
  url: 'http://10.206.129.94:8000/#/login',
  intro: '为工艺、研发、质量等团队提供数据分析的系统',
},
{
  name: 'ESOP-江阴',
  fullName: 'ESOP',
  category: '大制造',
  url: 'http://esop.envision-aesc.cn/',
  intro: 'WI/OI, 点巡检Checklist',
},
{
  name: 'ESOP-鄂尔多斯',
  fullName: 'ESOP',
  category: '大制造',
  url: 'http://ordos-esop.envision-aesc.cn/',
  intro: 'WI/OI, 点巡检Checklist',
},
{
  name: 'MaaS-江阴Lab',
  fullName: 'Machine as a Service',
  category: '大制造',
  url: '江阴Lab：http://10.202.8.74:9094/#/login',
},
{
  name: 'MaaS-Ordos',
  fullName: 'Machine as a Service',
  category: '大制造',
  url: '鄂尔多斯：http://10.205.129.45:9094/#/login',
},
{
  name: 'MaaS-十堰',
  fullName: 'Machine as a Service',
  category: '大制造',
  url: '十堰：http://10.206.129.53:9094/#/login',
},
{
  name: 'MaaS-江阴NCM4',
  fullName: 'Machine as a Service',
  category: '大制造',
  url: '江阴NCM4:http://10.202.33.130:9094/#/login',
  intro: '设备集成&边缘物联平台',
},
{
  name: 'MES-江阴一期',
  fullName: '制造执行系统',
  category: '大制造',
  url: '江阴一期：http://cpec-mes.envision-aesc.cn/apriso/start/?track=client',
  intro: '面向车间生产制造管理系统',
},
{
  name: 'MES-Ordos',
  fullName: '制造执行系统',
  category: '大制造',
  url: '鄂尔多斯：http://ordos-mes.envision-aesc.cn/apriso/start/?track=client',
  intro: '面向车间生产制造管理系统',
},
{
  name: 'MES-十堰',
  fullName: '制造执行系统',
  category: '大制造',
  url: '十堰：http://10.206.134.80/apriso/apriso/#/search',
  intro: '面向车间生产制造管理系统',
},
{
  name: 'FMS',
  fullName: '基建项目管理系统',
  category: '大质量',
  url: 'http://g-fms.envision-aesc.cn:1080/login',
  intro: '基础建设项目管理系统(工程中心)',
},
{
  name: 'APQP',
  fullName: '产品质量先期策划系统',
  category: '大质量',
  url: 'https://s-apqp.envision-aesc.cn:1080/login',
  intro: '主要是SQE用来管理以及审批供应商提交的PPAP以及apqp文档的管理系统',
},
{
  name: 'QMS-IQC',
  fullName: '质量管理系统',
  category: '大质量',
  url: 'http://qms.envision-aesc.cn:8001/',
  intro: '来料质量检验',
},
{
  name: 'QMS-内审',
  fullName: '质量管理系统',
  category: '大质量',
  url: 'http://qms.envision-aesc.cn:8010/',
  intro: '质量检验审核流程管理',
},
{
  name: 'IMS',
  fullName: '问题管理系统',
  category: '大质量',
  url: 'http://qrqc.envision-aesc.cn/user/login',
  intro: '管理客诉问题，I&II问题，质量巡检问题，售后提单，TVC测试问题',
},
{
  name: 'ECOA',
  fullName: '供应商出货检验系统',
  category: '大质量',
  url: 'https://ecoa.envision-aesc.cn:9300/#/login',
  intro: '供应商管理，物料管理，检验项管理，检验计划，物料检验单',
},
{
  name: 'SPC-十堰',
  fullName: '统计过程分析系统',
  category: '大质量',
  url: '十堰SPC: http://10.206.129.96:6003/#/login',
  intro: 'SPC应用统计分析技术对生产过程进行实时监控，科学的区分出生产过程中产品质量的随机波动与异常波动，从而对生产过程的异常趋势提出预警，以便生产管理人员及时采取措施，消除异常，恢复过程的稳定，从而达到提高和控制质量的目的。',
},
{
  name: 'SPC-江阴',
  fullName: '统计过程分析系统',
  category: '大质量',
  url: '江阴SPC: http://10.202.12.123:6003/#/login',
  intro: 'SPC应用统计分析技术对生产过程进行实时监控，科学的区分出生产过程中产品质量的随机波动与异常波动，从而对生产过程的异常趋势提出预警，以便生产管理人员及时采取措施，消除异常，恢复过程的稳定，从而达到提高和控制质量的目的。',
},
{
  name: 'SPC-Ordos',
  fullName: '统计过程分析系统',
  category: '大质量',
  url: '鄂尔多斯SPC: http://spc-ordos.envision-aesc.cn/#/login',
  intro: 'SPC应用统计分析技术对生产过程进行实时监控，科学的区分出生产过程中产品质量的随机波动与异常波动，从而对生产过程的异常趋势提出预警，以便生产管理人员及时采取措施，消除异常，恢复过程的稳定，从而达到提高和控制质量的目的。',
},
]

// add logo property to each item of apps
apps.forEach((app) => {
  // app.logo = ''
})

// push 40 test items to apps
/*
for (let i = 0; i < 40; i++) {
  apps.push({
    name: `Test${i}`,
    fullName: `Test${i}`,
    category: '',
    url: `http://tech.envision-aesc.cn/test${i}`,
    intro: `Test${i}`,
    // x: 1,
    // y: 1,
    // w: 1,
    // h: 1,
  })
}
*/

// export apps
export default apps
