/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheGrid: typeof import('./components/widget/TheGrid.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheWidget: typeof import('./components/widget/TheWidget.vue')['default']
    TimeNow: typeof import('./components/widget/TimeNow.vue')['default']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarLink: typeof import('@varlet/ui')['_LinkComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
  }
}
